apiVersion: v1
kind: Secret
metadata:
  name: aidevelo-app-secrets
  namespace: aidevelo
type: Opaque
stringData:
  BETTER_AUTH_SECRET: "replace-with-a-random-32-plus-char-secret"
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
